### ISSUE TITLE
[TASK] Set up CI/CD pipeline with GitHub Actions

### ISSUE THREAD

**Issue by fabricio-entringer** [fabricio-entringer/6mlet-tech-challenge-01#25]
## Description
Set up CI/CD pipeline with GitHub Actions for automated testing, code quality checks, and deployment automation to ensure code quality and streamlined development workflow.

## Requirements
- Configure GitHub Actions workflows for CI/CD
- Set up automated testing on pull requests and pushes
- Implement code quality checks (linting, type checking)
- Add automated dependency vulnerability scanning
- Configure automatic deployment to staging/production
- Implement test coverage reporting
- Add automated Docker image building and publishing

## Acceptance Criteria
- [ ] GitHub Actions workflow for continuous integration
- [ ] Automated testing on every PR and push to main
- [ ] Code quality checks (Black, Flake8, mypy)
- [ ] Test coverage reporting and enforcement
- [ ] Dependency vulnerability scanning
- [ ] Automated Docker image building
- [ ] Deployment pipeline to staging environment
- [ ] Production deployment with manual approval
- [ ] Status badges in README for build status
- [ ] Notification setup for build failures

## Workflow Structure
```yaml
# .github/workflows/ci.yml
name: CI/CD Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    # Testing, linting, coverage
  build:
    # Docker image building
  deploy:
    # Deployment to environments
```

## CI/CD Features
- Run tests on multiple Python versions
- Code quality enforcement
- Security vulnerability scanning
- Automated deployment pipelines
- Build and push Docker images
- Environment-specific deployments

## Dependencies
- Requires comprehensive test suite
- Requires Docker configuration

## Priority
Medium - Important for development workflow
